### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by gokaygurcan** [woguan/Legend-Wings#1]
Hello,

Just out of curiosity, why don't you use regular checkboxes? 

- [x] a complete item
- [ ] an incomplete item

Nice work btw, thanks!

**Comment by woguan** [comment]
Hii,

Just to be unique, haha. No other reasons. I'm also planning to move the Todo's to another place like a blog or something. I need some time for that though.

**Comment by gokaygurcan** [comment]
Nice! Thanks ;)
