### ISSUE TITLE
Game Crashing after loading on iPhone 5s

### ISSUE THREAD

**Issue by Quaggie** [woguan/Legend-Wings#2]
After building and running the game on my iPhone, the loading goes up to 100% then it crashes.
The picture of the occurring error is shown below.

**Specs**
* iPhone 5s 16gb
* iOS 11 beta 3

![screen shot 2017-07-11 at 11 52 16](https://user-images.githubusercontent.com/11230276/28074647-7c75b688-662f-11e7-94df-36871ec3aa53.png)

**Comment by woguan** [comment]
Thank you for reporting. 

I have fixed this issue.
